#ifndef SP_CONTROLLER_H_
#define SP_CONTROLLER_H_

#include <pthread.h>

extern void *spRun(void *ptr_thread_data);

// Switch Panel
#define sSP_MAGNETOS_OFF_1_CR               "sim/magnetos/magnetos_off_1"
#define sSP_MAGNETOS_OFF_2_CR               "sim/magnetos/magnetos_off_2"
#define sSP_MAGNETOS_OFF_3_CR               "sim/magnetos/magnetos_off_3"
#define sSP_MAGNETOS_OFF_4_CR               "sim/magnetos/magnetos_off_4"
#define sSP_MAGNETOS_OFF_5_CR               "sim/magnetos/magnetos_off_5"
#define sSP_MAGNETOS_OFF_6_CR               "sim/magnetos/magnetos_off_6"
#define sSP_MAGNETOS_OFF_7_CR               "sim/magnetos/magnetos_off_7"
#define sSP_MAGNETOS_OFF_8_CR               "sim/magnetos/magnetos_off_8"
#define sSP_MAGNETOS_RIGHT_1_CR             "sim/magnetos/magnetos_right_1"
#define sSP_MAGNETOS_RIGHT_2_CR             "sim/magnetos/magnetos_right_2"
#define sSP_MAGNETOS_RIGHT_3_CR             "sim/magnetos/magnetos_right_3"
#define sSP_MAGNETOS_RIGHT_4_CR             "sim/magnetos/magnetos_right_4"
#define sSP_MAGNETOS_RIGHT_5_CR             "sim/magnetos/magnetos_right_5"
#define sSP_MAGNETOS_RIGHT_6_CR             "sim/magnetos/magnetos_right_6"
#define sSP_MAGNETOS_RIGHT_7_CR             "sim/magnetos/magnetos_right_7"
#define sSP_MAGNETOS_RIGHT_8_CR             "sim/magnetos/magnetos_right_8"
#define sSP_MAGNETOS_LEFT_1_CR              "sim/magnetos/magnetos_left_1"
#define sSP_MAGNETOS_LEFT_2_CR              "sim/magnetos/magnetos_left_2"
#define sSP_MAGNETOS_LEFT_3_CR              "sim/magnetos/magnetos_left_3"
#define sSP_MAGNETOS_LEFT_4_CR              "sim/magnetos/magnetos_left_4"
#define sSP_MAGNETOS_LEFT_5_CR              "sim/magnetos/magnetos_left_5"
#define sSP_MAGNETOS_LEFT_6_CR              "sim/magnetos/magnetos_left_6"
#define sSP_MAGNETOS_LEFT_7_CR              "sim/magnetos/magnetos_left_7"
#define sSP_MAGNETOS_LEFT_8_CR              "sim/magnetos/magnetos_left_8"
#define sSP_MAGNETOS_BOTH_1_CR              "sim/magnetos/magnetos_both_1"
#define sSP_MAGNETOS_BOTH_2_CR              "sim/magnetos/magnetos_both_2"
#define sSP_MAGNETOS_BOTH_3_CR              "sim/magnetos/magnetos_both_3"
#define sSP_MAGNETOS_BOTH_4_CR              "sim/magnetos/magnetos_both_4"
#define sSP_MAGNETOS_BOTH_5_CR              "sim/magnetos/magnetos_both_5"
#define sSP_MAGNETOS_BOTH_6_CR              "sim/magnetos/magnetos_both_6"
#define sSP_MAGNETOS_BOTH_7_CR              "sim/magnetos/magnetos_both_7"
#define sSP_MAGNETOS_BOTH_8_CR              "sim/magnetos/magnetos_both_8"
#define sSP_ENGINE_START_1_CR               "sim/starters/engage_starter_1"
#define sSP_ENGINE_START_2_CR               "sim/starters/engage_starter_2"
#define sSP_ENGINE_START_3_CR               "sim/starters/engage_starter_3"
#define sSP_ENGINE_START_4_CR               "sim/starters/engage_starter_4"
#define sSP_ENGINE_START_5_CR               "sim/starters/engage_starter_5"
#define sSP_ENGINE_START_6_CR               "sim/starters/engage_starter_6"
#define sSP_ENGINE_START_7_CR               "sim/starters/engage_starter_7"
#define sSP_ENGINE_START_8_CR               "sim/starters/engage_starter_8"

#define sSP_MASTER_BATTERY_ON_CR          "sim/electrical/battery_1_on"
#define sSP_MASTER_BATTERY_OFF_CR         "sim/electrical/battery_1_off"
#define sSP_MASTER_ALT_BATTERY_ON_CR      "sim/electrical/battery_2_on"
#define sSP_MASTER_ALT_BATTERY_OFF_CR     "sim/electrical/battery_2_off"

#define sSP_GENERATOR_ON_1_CR               "sim/electrical/generator_1_on"
#define sSP_GENERATOR_OFF_1_CR              "sim/electrical/generator_1_off"
#define sSP_GENERATOR_ON_2_CR               "sim/electrical/generator_2_on"
#define sSP_GENERATOR_OFF_2_CR              "sim/electrical/generator_2_off"
#define sSP_GENERATOR_ON_3_CR               "sim/electrical/generator_3_on"
#define sSP_GENERATOR_OFF_3_CR              "sim/electrical/generator_3_off"
#define sSP_GENERATOR_ON_4_CR               "sim/electrical/generator_4_on"
#define sSP_GENERATOR_OFF_4_CR              "sim/electrical/generator_4_off"
#define sSP_GENERATOR_ON_5_CR               "sim/electrical/generator_5_on"
#define sSP_GENERATOR_OFF_5_CR              "sim/electrical/generator_5_off"
#define sSP_GENERATOR_ON_6_CR               "sim/electrical/generator_6_on"
#define sSP_GENERATOR_OFF_6_CR              "sim/electrical/generator_6_off"
#define sSP_GENERATOR_ON_7_CR               "sim/electrical/generator_7_on"
#define sSP_GENERATOR_OFF_7_CR              "sim/electrical/generator_7_off"
#define sSP_GENERATOR_ON_8_CR               "sim/electrical/generator_8_on"
#define sSP_GENERATOR_OFF_8_CR              "sim/electrical/generator_8_off"

#define sSP_MASTER_AVIONICS_ON_CR         "sim/systems/avionics_on"
#define sSP_MASTER_AVIONICS_OFF_CR        "sim/systems/avionics_off"
#define sSP_FUEL_PUMP_ON_1_CR             "sim/fuel/fuel_pump_1_on"
#define sSP_FUEL_PUMP_OFF_1_CR            "sim/fuel/fuel_pump_1_off"
#define sSP_FUEL_PUMP_ON_2_CR             "sim/fuel/fuel_pump_2_on"
#define sSP_FUEL_PUMP_OFF_2_CR            "sim/fuel/fuel_pump_2_off"
#define sSP_FUEL_PUMP_ON_3_CR             "sim/fuel/fuel_pump_3_on"
#define sSP_FUEL_PUMP_OFF_3_CR            "sim/fuel/fuel_pump_3_off"
#define sSP_FUEL_PUMP_ON_4_CR             "sim/fuel/fuel_pump_4_on"
#define sSP_FUEL_PUMP_OFF_4_CR            "sim/fuel/fuel_pump_4_off"
#define sSP_FUEL_PUMP_ON_5_CR             "sim/fuel/fuel_pump_5_on"
#define sSP_FUEL_PUMP_OFF_5_CR            "sim/fuel/fuel_pump_5_off"
#define sSP_FUEL_PUMP_ON_6_CR             "sim/fuel/fuel_pump_6_on"
#define sSP_FUEL_PUMP_OFF_6_CR            "sim/fuel/fuel_pump_6_off"
#define sSP_FUEL_PUMP_ON_7_CR             "sim/fuel/fuel_pump_7_on"
#define sSP_FUEL_PUMP_OFF_7_CR            "sim/fuel/fuel_pump_7_off"
#define sSP_FUEL_PUMP_ON_8_CR             "sim/fuel/fuel_pump_8_on"
#define sSP_FUEL_PUMP_OFF_8_CR            "sim/fuel/fuel_pump_8_off"
#define sSP_DE_ICE_ON_CR                  "sim/ice/detect_on"
#define sSP_DE_ICE_OFF_CR                 "sim/ice/detect_off"
#define sSP_PITOT_HEAT_ON_CR              "sim/ice/pitot_heat_on"
#define sSP_PITOT_HEAT_OFF_CR             "sim/ice/pitot_heat_off"

#define sSP_COWL_CLOSED_CR                "sim/flight_controls/cowl_flaps_closed"
#define sSP_COWL_OPEN_CR                  "sim/flight_controls/cowl_flaps_open"

#define sSP_LIGHTS_PANEL_ON_CR            "sim/instruments/panel_bright_down"
#define sSP_LIGHTS_PANEL_OFF_CR           "sim/instruments/panel_bright_up"
#define sSP_LIGHTS_BEACON_ON_CR           "sim/lights/beacon_lights_on"
#define sSP_LIGHTS_BEACON_OFF_CR          "sim/lights/beacon_lights_off"
#define sSP_LIGHTS_NAV_ON_CR              "sim/lights/nav_lights_on"
#define sSP_LIGHTS_NAV_OFF_CR             "sim/lights/nav_lights_off"
#define sSP_LIGHTS_STROBE_ON_CR           "sim/lights/strobe_lights_on"
#define sSP_LIGHTS_STROBE_OFF_CR          "sim/lights/strobe_lights_off"
#define sSP_LIGHTS_TAXI_ON_CR             "sim/lights/taxi_lights_on"
#define sSP_LIGHTS_TAXI_OFF_CR            "sim/lights/taxi_lights_off"
#define sSP_LIGHTS_LANDING_ON_CR          "sim/lights/landing_lights_on"
#define sSP_LIGHTS_LANDING_OFF_CR         "sim/lights/landing_lights_off"

#define sSP_LANDING_GEAR_UP_CR            "sim/flight_controls/landing_gear_down"
#define sSP_LANDING_GEAR_DOWN_CR          "sim/flight_controls/landing_gear_up"

#define sSP_NUMBER_OF_BATTERIES_DR        "sim/aircraft/electrical/num_batteries"
#define sSP_NUMBER_OF_GENERATORS_DR       "sim/aircraft/electrical/num_generators"
#define sSP_NUMBER_OF_ENGINES_DR          "sim/aircraft/engine/acf_num_engines"
#define sSP_BATTERY_ARRAY_ON_DR           "sim/cockpit/electrical/battery_array_on"
#define sSP_ON_GROUND_DR                  "sim/flightmodel/failures/onground_any"
#define sSP_GEAR_1_FAIL_DR                "sim/operation/failures/rel_lagear1"
#define sSP_GEAR_2_FAIL_DR                "sim/operation/failures/rel_lagear2"
#define sSP_GEAR_3_FAIL_DR                "sim/operation/failures/rel_lagear3"
#define sSP_LANDING_GEAR_STATUS_DR        "sim/aircraft/parts/acf_gear_deploy"
#define sSP_GEAR_RETRACT_DR               "sim/aircraft/gear/acf_gear_retract"
#define sSP_ANTI_ICE_DR                   "sim/cockpit/switches/anti_ice_on"
#define sSP_COCKPIT_LIGHTS_DR             "sim/cockpit/electrical/cockpit/lights"
#define sSP_COWL_FLAPS_DR                 "sim/flightmodel/engine/ENGN_cowl"

#endif /* SP_CONTROLLER_H_ */
